name: Wiki

env:
  HUGO_VERSION: 0.71.0
  WIKIER_VERSION: 0.1
  EC2_HOST: doc.lottowawa.com 
  EC2_PORT: ec2-user
  EC2_USERNAME: ec2-user
  EC2_KEY: ${{ secrets.EC2_DOC_KEY }}
  # OWNER: n1ce37
  # REPOSITORY: lottery.wiki
on:
  gollum

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: debug
      run: echo $GITHUB_REPOSITORY
    
    - name: Check out wiki
      uses: actions/checkout@v2
      with:
        repository: n1ce37/lottery.git
        path: wiki

    - name: Check out hugo
      uses: actions/checkout@v2
      with:
        path: hugo

    - run: ls -lR ${GITHUB_WORKSPACE}

    - name: install hugo
      working-directory: /tmp
      run: |
        sudo curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo.tgz
        tar -zxvf hugo.tgz
        sudo mv hugo /usr/bin
        sudo chmod +x /usr/bin/hugo

    - name: install wikier
      run: |
        ls -lR ${GITHUB_WORKSPACE}
        sudo curl -L https://github.com/masschaos/wikier/releases/download/${WIKIER_VERSION}/main -o /usr/bin/wikier
        sudo chmod +x /usr/bin/wikier
    
    - name: run wikier for fix and move files
      run: |
        wikier ${GITHUB_WORKSPACE}

    - name: tar public files
      run: tar zcvf public.tgz public
      working-directory: ${GITHUB_WORKSPACE}/hugo/.hugo

    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${ EC2_HOST }
        username: ${ EC2_USERNAME }
        key: ${ EC2_KEY }
        port: ${ EC2_PORT }
        source: "${ GITHUB_WORKSPACE }/hugo/.hugo/public.tgz"
        target: ""

        #   - name: Slack Success Notification
        # if: success()
        # uses: rtCamp/action-slack-notify@master
        # env:
        #   SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #   SLACK_MESSAGE: "监控到 master 分支的 openapi.yaml 有变动，已发布到 https://doc.lottowawa.com"
        #   SLACK_TITLE: 文档发布成功